version: '2.1'
orbs:
  android: circleci/android:current
  flutter: circleci/flutter:current
jobs:
  distribute:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 3.2.6
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem
      - run:
          command: bundle exec fastlane distribute
          working_directory: ios
workflows:
  test:
    jobs:
      - flutter/unit_test
