version: '2.1'
orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.2
jobs:
  distribute:
    executor:
      name: android/android-machine
    steps:
      - flutter/install_sdk_and_pub:
          version: 2.17.5
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem
      - run:
          command: bundle exec fastlane distribute
          working_directory: ios
workflows:
  test:
    jobs:
      - flutter/unit_test
